import type { ModelInfo } from "../core/interfaces.js";

export const MODEL_DATA: ModelInfo[] = [
  // OpenAI Models
  {
    id: "gpt-4o",
    provider: "openai",
    name: "GPT-4o",
    contextWindow: 128000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: true,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: true,
    },
    pricing: { inputTokens: 2.5, outputTokens: 10.0 },
  },
  {
    id: "gpt-4o-mini",
    provider: "openai",
    name: "GPT-4o Mini",
    contextWindow: 128000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: true,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: true,
    },
    pricing: { inputTokens: 0.15, outputTokens: 0.6 },
  },
  {
    id: "gpt-4-turbo",
    provider: "openai",
    name: "GPT-4 Turbo",
    contextWindow: 128000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: true,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: true,
    },
    pricing: { inputTokens: 10.0, outputTokens: 30.0 },
  },
  {
    id: "gpt-4",
    provider: "openai",
    name: "GPT-4",
    contextWindow: 8192,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: false,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: false,
    },
    pricing: { inputTokens: 30.0, outputTokens: 60.0 },
  },
  {
    id: "gpt-3.5-turbo",
    provider: "openai",
    name: "GPT-3.5 Turbo",
    contextWindow: 16385,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: false,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: false,
    },
    pricing: { inputTokens: 0.5, outputTokens: 1.5 },
  },
  {
    id: "o1-preview",
    provider: "openai",
    name: "o1-preview",
    contextWindow: 200000,
    capabilities: {
      streaming: true,
      functionCalling: false,
      vision: false,
      audio: false,
      embeddings: false,
      reasoning: true,
      video: false,
      documents: false,
    },
    pricing: { inputTokens: 15.0, outputTokens: 60.0 },
  },
  {
    id: "o1-mini",
    provider: "openai",
    name: "o1-mini",
    contextWindow: 200000,
    capabilities: {
      streaming: true,
      functionCalling: false,
      vision: false,
      audio: false,
      embeddings: false,
      reasoning: true,
      video: false,
      documents: false,
    },
    pricing: { inputTokens: 3.0, outputTokens: 12.0 },
  },

  // Anthropic Models
  {
    id: "claude-3-5-sonnet-20240620",
    provider: "anthropic",
    name: "Claude 3.5 Sonnet",
    contextWindow: 200000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: true,
      audio: false,
      embeddings: false,
      reasoning: false,
      documents: true,
    },
    pricing: { inputTokens: 3.0, outputTokens: 15.0 },
  },
  {
    id: "claude-3-opus-20240229",
    provider: "anthropic",
    name: "Claude 3 Opus",
    contextWindow: 200000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: true,
      audio: false,
      embeddings: false,
      reasoning: false,
      documents: true,
    },
    pricing: { inputTokens: 15.0, outputTokens: 75.0 },
  },
  {
    id: "claude-3-sonnet-20240229",
    provider: "anthropic",
    name: "Claude 3 Sonnet",
    contextWindow: 200000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: true,
      audio: false,
      embeddings: false,
      reasoning: false,
      documents: true,
    },
    pricing: { inputTokens: 3.0, outputTokens: 15.0 },
  },
  {
    id: "claude-3-haiku-20240307",
    provider: "anthropic",
    name: "Claude 3 Haiku",
    contextWindow: 200000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: true,
      audio: false,
      embeddings: false,
      reasoning: false,
      documents: true,
    },
    pricing: { inputTokens: 0.25, outputTokens: 1.25 },
  },

  // Google Gemini Models
  {
    id: "gemini-2.0-flash-exp",
    provider: "gemini",
    name: "Gemini 2.0 Flash (Experimental)",
    contextWindow: 1048576, // 1M tokens
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: true,
      audio: true,
      embeddings: false,
      reasoning: true,
      video: true,
      documents: true,
    },
    pricing: { inputTokens: 0.075, outputTokens: 0.3 },
  },
  {
    id: "gemini-1.5-pro",
    provider: "gemini",
    name: "Gemini 1.5 Pro",
    contextWindow: 2097152, // 2M tokens
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: true,
      audio: true,
      embeddings: false,
      reasoning: false,
      video: true,
      documents: true,
    },
    pricing: { inputTokens: 1.25, outputTokens: 5.0 },
  },
  {
    id: "gemini-1.5-flash",
    provider: "gemini",
    name: "Gemini 1.5 Flash",
    contextWindow: 1048576, // 1M tokens
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: true,
      audio: true,
      embeddings: false,
      reasoning: false,
      video: true,
      documents: true,
    },
    pricing: { inputTokens: 0.075, outputTokens: 0.3 },
  },

  // Cohere Models
  {
    id: "command-r-plus",
    provider: "cohere",
    name: "Command R+",
    contextWindow: 128000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: false,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: true,
    },
    pricing: { inputTokens: 3.0, outputTokens: 15.0 },
  },
  {
    id: "command-r",
    provider: "cohere",
    name: "Command R",
    contextWindow: 128000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: false,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: true,
    },
    pricing: { inputTokens: 0.5, outputTokens: 1.5 },
  },
  {
    id: "command-light",
    provider: "cohere",
    name: "Command Light",
    contextWindow: 4096,
    capabilities: {
      streaming: true,
      functionCalling: false,
      vision: false,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: false,
    },
    pricing: { inputTokens: 0.3, outputTokens: 0.6 },
  },
  // Cohere Embedding Models
  {
    id: "embed-english-v3.0",
    provider: "cohere",
    name: "Embed English v3.0",
    contextWindow: 512,
    capabilities: {
      streaming: false,
      functionCalling: false,
      vision: false,
      audio: false,
      embeddings: true,
      reasoning: false,
      video: false,
      documents: false,
    },
    pricing: { inputTokens: 0.1, outputTokens: 0.0 },
  },
  {
    id: "embed-multilingual-v3.0",
    provider: "cohere",
    name: "Embed Multilingual v3.0",
    contextWindow: 512,
    capabilities: {
      streaming: false,
      functionCalling: false,
      vision: false,
      audio: false,
      embeddings: true,
      reasoning: false,
      video: false,
      documents: false,
    },
    pricing: { inputTokens: 0.1, outputTokens: 0.0 },
  },

  // Mistral Models
  {
    id: "mistral-large-latest",
    provider: "mistral",
    name: "Mistral Large Latest",
    contextWindow: 128000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: false,
      audio: false,
      embeddings: false,
      reasoning: true,
      video: false,
      documents: true,
    },
    pricing: { inputTokens: 3.0, outputTokens: 9.0 },
  },
  {
    id: "pixtral-large-latest",
    provider: "mistral",
    name: "Pixtral Large Latest",
    contextWindow: 128000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: true,
      audio: false,
      embeddings: false,
      reasoning: true,
      video: false,
      documents: true,
    },
    pricing: { inputTokens: 3.0, outputTokens: 9.0 },
  },
  {
    id: "mistral-small-latest",
    provider: "mistral",
    name: "Mistral Small Latest",
    contextWindow: 32000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: false,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: true,
    },
    pricing: { inputTokens: 1.0, outputTokens: 3.0 },
  },
  {
    id: "codestral-2501",
    provider: "mistral",
    name: "Codestral 2501",
    contextWindow: 256000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: false,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: true,
    },
    pricing: { inputTokens: 1.0, outputTokens: 3.0 },
  },
  {
    id: "open-mistral-nemo",
    provider: "mistral",
    name: "Mistral Nemo 12B",
    contextWindow: 128000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: false,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: false,
    },
    pricing: { inputTokens: 0.3, outputTokens: 0.3 },
  },
  {
    id: "pixtral-12b-latest",
    provider: "mistral",
    name: "Pixtral 12B Latest",
    contextWindow: 128000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: true,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: false,
    },
    pricing: { inputTokens: 0.15, outputTokens: 0.15 },
  },
  {
    id: "ministral-8b-2410",
    provider: "mistral",
    name: "Ministral 8B",
    contextWindow: 128000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: false,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: false,
    },
    pricing: { inputTokens: 0.1, outputTokens: 0.1 },
  },
  {
    id: "ministral-3b-2410",
    provider: "mistral",
    name: "Ministral 3B",
    contextWindow: 128000,
    capabilities: {
      streaming: true,
      functionCalling: false,
      vision: false,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: false,
    },
    pricing: { inputTokens: 0.04, outputTokens: 0.04 },
  },
  // Mistral Embedding Models
  {
    id: "mistral-embed",
    provider: "mistral",
    name: "Mistral Embed",
    contextWindow: 8192,
    capabilities: {
      streaming: false,
      functionCalling: false,
      vision: false,
      audio: false,
      embeddings: true,
      reasoning: false,
      video: false,
      documents: false,
    },
    pricing: { inputTokens: 0.1, outputTokens: 0.0 },
  },

  // OpenRouter Models (Popular Selections)
  {
    id: "openai/gpt-4o",
    provider: "openrouter",
    name: "GPT-4o (OpenRouter)",
    contextWindow: 128000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: true,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: true,
    },
    pricing: { inputTokens: 5.0, outputTokens: 15.0 },
  },
  {
    id: "openai/gpt-4o-mini",
    provider: "openrouter",
    name: "GPT-4o Mini (OpenRouter)",
    contextWindow: 128000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: true,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: true,
    },
    pricing: { inputTokens: 0.15, outputTokens: 0.6 },
  },
  {
    id: "anthropic/claude-3.5-sonnet",
    provider: "openrouter",
    name: "Claude 3.5 Sonnet (OpenRouter)",
    contextWindow: 200000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: true,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: true,
    },
    pricing: { inputTokens: 3.0, outputTokens: 15.0 },
  },
  {
    id: "anthropic/claude-3.5-haiku",
    provider: "openrouter",
    name: "Claude 3.5 Haiku (OpenRouter)",
    contextWindow: 200000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: true,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: true,
    },
    pricing: { inputTokens: 0.8, outputTokens: 4.0 },
  },
  {
    id: "google/gemini-2.0-flash-exp",
    provider: "openrouter",
    name: "Gemini 2.0 Flash (OpenRouter)",
    contextWindow: 1048576,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: true,
      audio: true,
      embeddings: false,
      reasoning: false,
      video: true,
      documents: true,
    },
    pricing: { inputTokens: 0.075, outputTokens: 0.3 },
  },
  {
    id: "mistralai/mistral-large",
    provider: "openrouter",
    name: "Mistral Large (OpenRouter)",
    contextWindow: 128000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: false,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: true,
    },
    pricing: { inputTokens: 3.0, outputTokens: 9.0 },
  },
  {
    id: "mistralai/pixtral-large",
    provider: "openrouter",
    name: "Pixtral Large (OpenRouter)",
    contextWindow: 128000,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: true,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: true,
    },
    pricing: { inputTokens: 3.0, outputTokens: 9.0 },
  },
  {
    id: "meta-llama/llama-3.3-70b-instruct",
    provider: "openrouter",
    name: "Llama 3.3 70B Instruct (OpenRouter)",
    contextWindow: 131072,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: false,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: false,
    },
    pricing: { inputTokens: 0.59, outputTokens: 0.79 },
  },
  {
    id: "deepseek/deepseek-chat",
    provider: "openrouter",
    name: "DeepSeek Chat (OpenRouter)",
    contextWindow: 65536,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: false,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: false,
    },
    pricing: { inputTokens: 0.14, outputTokens: 0.28 },
  },
  {
    id: "qwen/qwen-2.5-72b-instruct",
    provider: "openrouter",
    name: "Qwen 2.5 72B Instruct (OpenRouter)",
    contextWindow: 32768,
    capabilities: {
      streaming: true,
      functionCalling: true,
      vision: false,
      audio: false,
      embeddings: false,
      reasoning: false,
      video: false,
      documents: false,
    },
    pricing: { inputTokens: 0.4, outputTokens: 0.4 },
  },
];
